apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadyexh1779-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadyexh1779-tenant-component
    app.kubernetes.io/part-of: loadyexh1779-tenant-app
  name: loadyexh1779-tenant-component
  namespace: loadyexh1779-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadyexh1779-tenant-component
    weight: null
status: {}
